--- # roles/myrepos/tasks/main.yml

- name: Load OS specific variables
  include_vars: "{{ fact_role_path }}/vars/{{ ansible_os_family | lower }}.yml"
  tags:
    - myrepos
    - install

- name: "Debug variable values"
  include_tasks: "{{ fact_role_path }}/tasks/debug.yml"
  when: myrepos_debug
  tags:
    - myrepos
    - debug

- name: Run any OS specific tasks
  include_tasks: "{{ fact_role_path }}/tasks/{{ ansible_os_family | lower }}.yml"
  tags:
    - myrepos
    - install

- name: "Run any tests"
  include_tasks: "{{ fact_role_path }}/tasks/tests.yml"
  when: myrepos_deployment_testing
  tags:
    - myrepos
    - test

